CC = c++

CFLAGS = -Wall -Wextra -Werror -std=c++98

NAME = BraiiiiiiinnnzzzZ

SRC = 

OBJ = $(SRC:.c=.o)

$(NAME) : $(OBJ)
	$(CC) $(CFLAGS) -o  $? $<

clean :
	rm -f $(OBJ)

fclean : clean
	rm -f $(NAME)

all : fclean 


